apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: market
  template:
    metadata:
      labels:
        app: market
    spec:
      containers:
        - name: api
          image: market-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          startupProbe:
            httpGet: {path: /health, port: 8000}
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            httpGet: {path: /health, port: 8000}
            periodSeconds: 10
          readinessProbe:
            httpGet: {path: /ready, port: 8000}
            periodSeconds: 5
          resources:
            requests: {cpu: 100m, memory: 1000Mi}
            limits: {cpu: "1", memory: 1000Mi}